version: "1"
services:
  client:
    build: ./client/
    ports: 
      - "99:80"
    depends_on:
      - server
  server:
    build: ./server/
    ports: 
      - "3000:9999"
    links:
      - "mongodb:db"
  mongodb:
    image: mongo
    command: -dbpath /dbdata
    volumes:
      - type: bind
        source: /dbdata
        target: /dbdata
