version: "3.2"
services:
  client:
    build: ./client/
    ports: 
      - "80:80"
    depends_on:
      - server
  server:
    build: ./server/
    ports: 
      - "9999:9999"
    links:
      - "mongodb:db"
    depends_on:
      - mongodb
    volumes:
      - type: bind
        source: /tasks
        target: /tasks
  mongodb:
    image: mongo
    command: -dbpath /dbdata
    volumes:
      - type: bind
        source: /dbdata
        target: /dbdata
